apiVersion: v1
kind: ReplicationController
metadata:
  name: mattermost-app
  labels:
    app: mattermost
    tier: app
  namespace: default
spec:
  replicas: 1
  selector:
    app: mattermost
    tier: app
  template:
    metadata:
      name: mattermost-app
      labels:
        app: mattermost
        tier: app
    spec:
      containers:
      - name: mattermost-app
        image: "mattermost/mattermost-prod-app"
        env:
        - name: DB_HOST
          value: "mattermost-db"
        volumeMounts:
        - name: appconfig
          mountPath: /mattermost/config
        - name: appdata
          mountPath: /mattermost/data
        - name: etclocaltime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: appconfig
        configMap:
          name: mattermost.config
      - name: appdata
        persistentVolumeClaim:
          claimName: mattermost-app
      - name: etclocaltime
        hostPath:
          path: /etc/localtime
